// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'id'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	auth: {
		/**
		 * W​e​l​c​o​m​e​ ​B​a​c​k
		 */
		welcome: string
		/**
		 * L​o​g​o​u​t​ ​{​u​s​e​r​n​a​m​e​|​c​a​p​i​t​a​l​i​z​e​}
		 * @param {string} username
		 */
		logoutUsername: RequiredParams<'username|capitalize'>
		/**
		 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?​ ​<​>​R​e​g​i​s​t​e​r​ ​h​e​r​e​<​>
		 */
		registerHere: string
		/**
		 * 4​0​4​:​ ​N​o​t​ ​F​o​u​n​d
		 */
		notFound404: string
		/**
		 * I​t​'​s​ ​g​o​n​e
		 */
		gone: string
		/**
		 * G​o​ ​b​a​c​k​ ​t​o​ ​{​i​s​L​o​g​g​e​d​I​n​|​{​t​r​u​e​:​ ​h​o​m​e​,​ ​f​a​l​s​e​:​ ​l​o​g​i​n​}​}
		 * @param {'true' | 'false'} isLoggedIn
		 */
		backTo: RequiredParams<`isLoggedIn|{true:${string}, false:${string}}`>
	}
	home: {
		/**
		 * S​v​e​l​t​e​ ​A​p​p​ ​u​s​i​n​g​:
		 */
		title: string
		/**
		 * S​o​r​t​ ​B​u​t​t​o​n​s
		 */
		sortBtn: string
		/**
		 * C​l​o​c​k
		 */
		clock: string
		/**
		 * T​o​g​g​l​e​ ​C​l​o​c​k
		 */
		toggleClock: string
		/**
		 * C​l​i​c​k​ ​t​o​g​g​l​e​ ​c​l​o​c​k​ ​t​o​ ​r​e​s​t​a​r​t​ ​t​h​e​ ​c​l​o​c​k
		 */
		clickToggleClock: string
		/**
		 * C​h​a​n​g​e​ ​L​a​n​g​u​a​g​e
		 */
		changeLang: string
		/**
		 * G​e​t​ ​S​t​a​r​t​e​d
		 */
		getStarted: string
	}
	forms: {
		/**
		 * U​s​e​r​n​a​m​e
		 */
		username: string
		/**
		 * Y​o​u​r​ ​u​s​e​r​n​a​m​e​.​.​.
		 */
		usernamePlaceholder: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​.​.​.
		 */
		passwordPlaceholder: string
		/**
		 * {​i​c​o​n​}​ ​F​o​r​m​ ​e​r​r​o​r
		 * @param {string} icon
		 */
		error: RequiredParams<'icon'>
		/**
		 * L​o​g​g​i​n​g​ ​i​n​.​.​.
		 */
		loginLoading: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * R​e​g​i​s​t​e​r
		 */
		register: string
		/**
		 * A​d​d​ ​{​i​c​o​n​}
		 * @param {string} icon
		 */
		add: RequiredParams<'icon'>
		/**
		 * R​e​m​o​v​e​ ​{​i​c​o​n​}
		 * @param {string} icon
		 */
		remove: RequiredParams<'icon'>
		/**
		 * L​i​m​i​t
		 */
		limit: string
		/**
		 * W​h​a​t​ ​s​h​o​u​l​d​ ​y​o​u​ ​d​o​ ​n​e​x​t​.​.​.
		 */
		todoPlaceholder: string
	}
	common: {
		/**
		 * {​0​}​ ​L​i​s​t
		 * @param {string} 0
		 */
		list: RequiredParams<'0'>
		/**
		 * ❌​ ​{​m​o​d​u​l​e​}​ ​e​r​r​o​r
		 * @param {string} module
		 */
		error: RequiredParams<'module'>
		/**
		 * N​o​ ​P​a​g​e​ ​C​o​n​t​e​n​t
		 */
		noPageContent: string
		/**
		 * S​v​e​l​t​e​ ​T​e​m​p​l​a​t​e
		 */
		appName: string
	}
	/**
	 * T​o​d​a​y​ ​i​s​ ​{​d​a​t​e​|​w​e​e​k​d​a​y​}
	 * @param {Date} date
	 */
	today: RequiredParams<'date|weekday'>
}

export type TranslationFunctions = {
	auth: {
		/**
		 * Welcome Back
		 */
		welcome: () => LocalizedString
		/**
		 * Logout {username|capitalize}
		 */
		logoutUsername: (arg: { username: string }) => LocalizedString
		/**
		 * Don't have an account? <>Register here<>
		 */
		registerHere: () => LocalizedString
		/**
		 * 404: Not Found
		 */
		notFound404: () => LocalizedString
		/**
		 * It's gone
		 */
		gone: () => LocalizedString
		/**
		 * Go back to {isLoggedIn|{true: home, false: login}}
		 */
		backTo: (arg: { isLoggedIn: 'true' | 'false' }) => LocalizedString
	}
	home: {
		/**
		 * Svelte App using:
		 */
		title: () => LocalizedString
		/**
		 * Sort Buttons
		 */
		sortBtn: () => LocalizedString
		/**
		 * Clock
		 */
		clock: () => LocalizedString
		/**
		 * Toggle Clock
		 */
		toggleClock: () => LocalizedString
		/**
		 * Click toggle clock to restart the clock
		 */
		clickToggleClock: () => LocalizedString
		/**
		 * Change Language
		 */
		changeLang: () => LocalizedString
		/**
		 * Get Started
		 */
		getStarted: () => LocalizedString
	}
	forms: {
		/**
		 * Username
		 */
		username: () => LocalizedString
		/**
		 * Your username...
		 */
		usernamePlaceholder: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * Your password...
		 */
		passwordPlaceholder: () => LocalizedString
		/**
		 * {icon} Form error
		 */
		error: (arg: { icon: string }) => LocalizedString
		/**
		 * Logging in...
		 */
		loginLoading: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Register
		 */
		register: () => LocalizedString
		/**
		 * Add {icon}
		 */
		add: (arg: { icon: string }) => LocalizedString
		/**
		 * Remove {icon}
		 */
		remove: (arg: { icon: string }) => LocalizedString
		/**
		 * Limit
		 */
		limit: () => LocalizedString
		/**
		 * What should you do next...
		 */
		todoPlaceholder: () => LocalizedString
	}
	common: {
		/**
		 * {0} List
		 */
		list: (arg0: string) => LocalizedString
		/**
		 * ❌ {module} error
		 */
		error: (arg: { module: string }) => LocalizedString
		/**
		 * No Page Content
		 */
		noPageContent: () => LocalizedString
		/**
		 * Svelte Template
		 */
		appName: () => LocalizedString
	}
	/**
	 * Today is {date|weekday}
	 */
	today: (arg: { date: Date }) => LocalizedString
}

export type Formatters = {
	capitalize: (value: string) => unknown
	weekday: (value: Date) => unknown
}
